### ISSUE TITLE
Payment status update issue

### ISSUE THREAD

**Issue by srksahoo** [simpliko/wpadverts#101]
Hi

When I change payment status, it is not being changed. it shows what is was previously.
Status is not changing as I want.

Please resolve the issue

Thanks

**Comment by gwin** [comment]
Hi,
thanks for the report, there seems to be a bug with the Payment Statuses (although changing status from the Payments History list still seem to work so you should be able to change them there).

We will have the issue fixed in the next release, in the meantime, you can email me using a contact form at https://wpadverts.com/contact/ i will send you back a quick fix.
