### ISSUE TITLE
Register Author and Manage Author shortcode failing

### ISSUE THREAD

**Issue by 14lisat** [simpliko/wpadverts#113]
When including shortcode [adverts_author_register] I get error in preview and publish, "updating failed" displayed in red banner on Edit Page. The same occurs for [adverts_author_manage].

[adverts_add] works

I have paid for an downloaded full add-on bundle previously. Recently added Authors paid add-on and included my license number using WP plugin UX. Concerned version of plugin is corrupt (accessed from an announcement for it somewhere) but cannot download and reinstall from your w/o paying for complete bundle a second time since this is the only option provided (different, UX bug you may want to consider i.e. add option to specify license number instead of purchase).

Please advise if I am missing something...

**Comment by gwin** [comment]
Thanks for the bug report, it is actually issue in the Authors extension, not in WPAdverts so i will move it there and close the thread here. 

It will be fixed in next Authors release. In the meantime you can have the error resolved by adding the code below in your theme functions.php file

    add_action( "init", function() {
        if( strpos($_SERVER[ 'REQUEST_URI' ], '/wp-json/') !== false ) {
            add_shortcode( "adverts_author_register", "__return_null" );
        }
    } );

If other shortcodes will cause a similar issue you can include them in the snippet by adding additional add_shortcode( "...", "__return_null" ); lines below the one that is already there, just replace ... with actual shortcode name which is causing the problem.

If you will still have a problem with it please contact the support using a contact form at https://wpadverts.com/contact/

I am not sure about the downloads, if you purchased an All Extensions Bundle less than a year ago you should be able to download all of the files including the Authors extension from your unique client panel link. If you do not have the client panel link please email me (via the contact form linked above) the email address you used to make a purchase or a license code, i will check it in the database and send you a client panel link back.
