### ISSUE TITLE
Styling issue

### ISSUE THREAD

**Issue by erikdemarco** [simpliko/wpadverts#146]
I tested with Fresh installed WP with only wpadverts as the plugin, no styling or modification. Then I tried to see how ad page looks like on most popular theme.

The problem mostly the contact button which placed far too left on the screen. 

WP 2020
![wpadverts-2020](https://user-images.githubusercontent.com/42645368/162581190-41ac3b36-861d-4ed3-92fb-a18fe93d1ef8.png)

WP-2021
![wpadverts-2021](https://user-images.githubusercontent.com/42645368/162581191-b22a823f-7111-4560-909a-82cbf1d32ffd.png)

WP-2022
![wpadverts-2022](https://user-images.githubusercontent.com/42645368/162581193-e87167f0-feba-4b27-896b-fa9debf1555e.png)

Astra
![wpadverts-astra](https://user-images.githubusercontent.com/42645368/162581195-1173abea-2e63-4e03-8a7c-36d30fa104f4.png)

**Comment by gwin** [comment]
This has more to do with the theme you are using rather than the plugin for example the WP-2022 has a full-width template only so the whole content is stretched.

You can change it by adding the code below in the wp-admin / Appearance / Customize / Additional CSS panel

```
.entry-content { width: 640px !important }
```

or if you know the ID of the page with the [adverts_add] shortcode then you can target this page specifically with something like

```
.page-id-100 .entry-content { width: 640px !important }
```

**Comment by gwin** [comment]
In the next release, the ad details content will be wrapped inside the ```<div>``` tag for easier justifying.
