### ISSUE TITLE
Image upload bug in 1.2.0 version

### ISSUE THREAD

**Issue by danielfsdo** [simpliko/wpadverts#46]
Hi,
I just update the plugin version and now the image upload don't work.  When I press the upload button the page just scroll top and nothing happens. 
Waiting for news.
Att,

**Comment by gwin** [comment]
Hi,
this indicates some kind of JavaScript error when clicking on the upload button.

You can either paste a link to a page where you are having this problem or while using Chrome, click Ctrl + Shift + i, this will open developer console, then try uploading a file again you should now see an error message which you can paste here.

**Comment by danielfsdo** [comment]
Ok, 
But, this happens just if I load the jQuery before your plugin scripts, and the error is in "includes/gallery.php" line 204 (where has a script).
If I dont load jquery, the plugin work fine, but my template needs jQuery load... 

The error is: 

Uncaught Error: Syntax error, unrecognized expression: <div class="wpadverts-overlay wpadverts-overlay-dark adverts-browser-frontend">...

How can I fix it?

**Comment by gwin** [comment]
How do you load the the jQuery? It should actually be the quite opposite, you should see a problem without the jQuery loaded as all of the WPAdverts scripts require jQuery.

Maybe you are loading some version different then bundled with WordPress?

Is there anything else in the error you sent? It is hard to tell what is causing an error like that. Maybe you could also post a screenshot? also, note that on the left side of the error message there should be an icon which you can click, it will expand the error message.

**Comment by danielfsdo** [comment]
The jQuery version that I load is 1.9.1.
The error print: 
![screen shot 2017-12-12 at 11 43 40 am](https://user-images.githubusercontent.com/4029301/33888106-346ae4ee-df33-11e7-8c22-c14b746bcd5b.png)

**Comment by gwin** [comment]
You are using older jQuery version, the bundled with WP 4.9 is 1.12, this might be a problem i suppose.

Additionally, the error you are having comes from the Sizzle library this is not something that is bundled with WP as well?

Either way, in your case just calling `jQuery("<div class='some-class'></div>")` seems to cause an error, but this should actually parse the HTML into object, at least with the default jQuery.

This is what happens in wpadverts/assets/js/adverts-gallery.js on line 404

`
var html = jQuery(compiled);
`

For me it seems the problem is with how you load the jQuery, you wrote that it works fine if you will not load jQuery at all, this is because if you will not load jQuery at all then WPAdverts will enqueue the default jQuery bundled with WP.

I suppose that when you explicitly load your jQuery it will include some additional libraries (like the Sizzle or maybe this is a part of jQuery 1.9 i cannot tell) which will break the Adverts Upload script.

**Comment by OezlemYi** [comment]
Hey @gwin,

ich have a similar problem. I get an error if I upload an image in frontend.
<img width="1908" alt="bildschirmfoto 2018-01-08 um 13 50 55" src="https://user-images.githubusercontent.com/17980990/34671458-0682de26-f47b-11e7-97d5-4a0273d4317a.png">
<img width="887" alt="bildschirmfoto 2018-01-08 um 13 51 05" src="https://user-images.githubusercontent.com/17980990/34671459-069de838-f47b-11e7-835b-629f5d8dcd55.png">

The jQuery version that I load is 1.11.4.

Att,

**Comment by danielfsdo** [comment]
@OezlemYi I just update the jQuery version to the last stable version and works fine. Try it.

**Comment by OezlemYi** [comment]
@danielfsdo updated jQuery and it works now. Thanks!
