### ISSUE TITLE
plug in

### ISSUE THREAD

**Issue by AresSolong** [simpliko/wpadverts#93]
Hi, I'm trying to install the plugin on wordpress, it tells me that I have to switch to the pro profile, I did it, I paid, I paid for it, but it doesn't let me install anything, it keeps telling me to switch to pro. what do I have to do?

**Comment by gwin** [comment]
Hi,
most likely you are on WordPress.com or some other Wordpress Managed Hosting (instead of WordPress.org) which does not allow installing plugins, you would need to either upgrade your hosting plan to "pro" plan or use some different hosting which allows installing plugins.

The WPAdverts itself does not have any kind of functionality which would require user to have some kind of "pro profile" to install it.

**Comment by AresSolong** [comment]
I'm on wordpress.org and I have a plan updated to the pro. the plugin is
correctly installed, he says, but as if it were not present.

Il giorno lun 27 mag 2019 alle ore 09:07 Greg Winiarski <
notifications@github.com> ha scritto:
